name: flutter_push_package
description: Firebase Package for AliothX
version: 1.0.2
homepage : https://github.com/reactspring
repository: https://github.com/reactspring/flutter_push_package.git
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_lg_health
  flutter_lg_health:
    path: ../../
  # Firebase Messaging Plugin for Flutter
  firebase_messaging: ^14.3.0
  # flutter_local_notifications
  flutter_local_notifications: ^9.4.0
  # Firebase In App Messaging Plugin for Flutter
  firebase_in_app_messaging: ^0.7.0+16
  # Shared preferences plugin
  shared_preferences: ^2.0.13
  # Device Info
  device_info_plus: ^3.1.1
  # Hive
  hive_flutter: ^1.1.0
  # A Flutter plugin for supporting secure storage of strings via Keychain and Keystore
  flutter_keychain: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
